name: chartjs
version: 0.5.0
description: Chart.js wrapper for Dart
author: Kevin Moore <kevmoo+github@google.com>
homepage: https://github.com/google/chartjs.dart/
environment:
  sdk: '>=1.13.1 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
