name: chartjs
version: 0.5.1
description: Chart.js wrapper for Dart
author: Kevin Moore <kevmoo+github@google.com>
homepage: https://github.com/google/chartjs.dart/
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^1.1.0
